# Generated by Django 3.0.5 on 2021-12-02 12:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300)),
                ('date', models.DateField(default=datetime.datetime(2021, 12, 2, 12, 27, 28, 64235, tzinfo=utc))),
                ('state', models.CharField(max_length=200)),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
            options={
                'db_table': 'weather',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(122.0)])),
                ('date', models.DateField(default=datetime.datetime(2021, 12, 2, 12, 27, 28, 64653, tzinfo=utc))),
                ('max', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(122.0)])),
                ('min', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(22)])),
                ('weather', models.ForeignKey(db_column='weather', on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='weather_app.Weather')),
            ],
            options={
                'db_table': 'temperature',
                'ordering': ('id', 'weather', 'date'),
                'unique_together': {('id', 'weather')},
            },
        ),
    ]
